### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by kamalkech** [graphql-go/subscription-example#1]
{
  "error": "Could not connect to websocket endpoint ws://localhost:3000/subscriptions. Please check if the endpoint url is correct."
}

**Comment by chris-ramon** [comment]
Hi @kamalkech, why would you try to use the endpoint: `ws://localhost:3000/subscriptions` ? 

The `README` shows that the endpoint to be used is:

```
localhost:8081/graphql
```

**Comment by kamalkech** [comment]
@chris-ramon for the port just i changed from 8081 to 3000, the error i have share is from frontend app using reactjs
